# Site settings
title:       oTree
email:       chris@otree.org
author:      Chris Wickens
description: "oTree : A software platform for economics experiments"
baseurl:     ""
url:         ""
url_docs:    "http://otree.readthedocs.org/en/latest/"
url_download: "http://otree.readthedocs.org/en/latest/setup.html"
url_tutorial: "http://otree.readthedocs.org/en/latest/tutorial/intro.html"
url_ztree: "http://otree.readthedocs.org/en/latest/ztree.html"
url_localization: "http://otree.readthedocs.org/en/latest/localization.html"

# Google analytics
google_analytics: UA-53910404-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: false
github_username:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
#markdown:     kramdown
markdown:     redcarpet
permalink:    pretty
paginate:     3
sass:
  compressed: true

